spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/test
    username: user
    password: password
    initialization-mode: always
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: create